package com.example.blmediagroup.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "CompanyDetails")
public class CompanyDetails {

    private String itemId;
    private String companyName;
    private String createdDate;
    private String slogan;
    private String emailContact;

    @DynamoDBHashKey(attributeName="ItemId") //partition key
    @DynamoDBAutoGeneratedKey
    public String getItemId() {
        return this.itemId;
    }


}
