package com.example.blmediagroup.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Testimony")
@DynamoDBDocument
public class Testimony {
    private String itemId;
    private String title;
    private String date;
    private String description;
    private String personName;

    private String createdDate;

    /* Getters */
    @DynamoDBHashKey(attributeName="ItemId") //partition key
    @DynamoDBAutoGeneratedKey
    public String getItemId() {
        return this.itemId;
    }

    @DynamoDBAttribute(attributeName="Title")
    public String getTitle(){
        return this.title;
    }

    @DynamoDBAttribute(attributeName="Date")
    public String getDate(){
        return this.date;
    }

    @DynamoDBAttribute(attributeName="Description")
    public String getDescription(){
        return this.description;
    }
    @DynamoDBAttribute(attributeName="PersonName")
    public String getPersonName(){
        return this.personName;
    }

    @DynamoDBAttribute(attributeName = "CreatedDate")
    public String getCreatedDate(){
        return this.createdDate;
    }

    /* Setters */
    public void setItemId(String itemId){
        this.itemId = itemId;
    }

    public void setTitle(String title){
        this.title = title;
    }

    public void setDate(String date){
        this.date = date;
    }

    public void setDescription(String description){
        this.description = description;
    }

    public void setPersonName(String personName){
        this.personName = personName;
    }

    public void setCreatedDate(String createdDate){
        this.createdDate = createdDate;
    }
}
